name: test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test_windows:
    strategy:
      matrix:
        os:
          - windows-latest
        node-version:
          - 22.x
        mssql-version:
          - ^11.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF even on Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Install mssql
        run: npm install --no-save mssql@${{ matrix.mssql-version }}

      - name: Lint
        run: npm run lint

      - name: Setup PostgreSQL for Linux/macOS/Windows
        uses: ikalnytskyi/action-setup-postgres@v7
        id: postgres
        env:
            POSTGRES_PASSWORD: postgrator
            POSTGRES_USER: postgrator
            POSTGRES_DB: postgrator
        with:
          port: 5432

      - name: Start databases
        run: docker compose up -d

      - name: Wait for databases to be available
        run: sleep 10

      - name: Test
        run: npm run cover
